2022 bms software
MST-MRDT/BmsBoardSoftware pull request #5
Opened 2022-04-24 21:20 UTC by bdavis2020

2022-04-24 21:23 UTC, bdavis2020 commented on BMS_Software.h
> +// Created for 2019 Valkyrie by: Jacob Lipina, jrlwd5
hmm

2022-04-24 21:25 UTC, bdavis2020 commented on BMS_Software.h
> +#define BUZZER_CTR_PIN			37
consistent indentation

2022-04-24 21:28 UTC, bdavis2020 commented on BMS_Software.h
> +// Tiva1294C RoveBoard Specs
teensy

2022-04-24 21:36 UTC, bdavis2020 commented on BMS_Software.h
> +#define CURRENT_MAX           	200000//mA; Current values must be sent over RoveComm as mA
should be 160000

2022-04-24 21:39 UTC, bdavis2020 commented on BMS_Software.h
> +#define CURRENT_MIN           	-196207//mA
for 2% error, 156800 mA; probably need to test and play with this number

2022-04-24 21:45 UTC, bdavis2020 commented on BMS_Software.h
> +#define CELL_COUNT	8// number of batteries
number of modules

2022-04-24 21:46 UTC, bdavis2020 commented on BMS_Software.h
> +#define CELL_UNDERVOLTAGE     2650 //mV //If any cell voltage reaches this voltage, turn off rover and BMS suicide.
2650 to 2400

2022-04-24 21:49 UTC, bdavis2020 commented on BMS_Software.h
> +#define PACK_UNDERVOLTAGE   	21600 //mV	//If pack voltage reaches this voltage, turn off rover and BMS suicide.
keep consistent with cell_undervoltage value

2022-04-24 21:50 UTC, MaxR-mrdt commented on BMS_Software.h
> +#define PACK_SAFETY_LOW     	PACK_UNDERVOLTAGE - 4000 //mV	//Even though I shouldn't be need to measure a voltage lower than undervoltage
not used, delete this

2022-04-24 21:51 UTC, MaxR-mrdt commented on BMS_Software.h
> +#define PACK_UNDERVOLTAGE   	21600 //mV	//If pack voltage reaches this voltage, turn off rover and BMS suicide.
undervoltage = 19200 mV
lowvoltage = 21200

2022-04-24 21:52 UTC, MaxR-mrdt commented on BMS_Software.h
> +#define PACK_SAFETY_LOW     	PACK_UNDERVOLTAGE - 4000 //mV	//Even though I shouldn't be need to measure a voltage lower than undervoltage
same with pack_effective_zero and cell_effective_zero

2022-04-24 22:00 UTC, ThisIsBrady commented on BMS_Software.ino
> +uint32_t time_since_Rovecomm_update = 0; // intial time of Rovecomm updating
use last_update_time

2022-04-24 22:10 UTC, ThisIsBrady commented on BMS_Software.ino
> +  batt_temp = (925 * (map(analogRead(TEMP_degC_MEAS_PIN), TEMP_ADC_MIN, TEMP_ADC_MAX, TEMP_MIN, TEMP_MAX)) / 1000); // mapping analog signals of battery temp data
What are the 1060 and 925 here? Maybe put them as consts

2022-04-24 22:20 UTC, ThisIsBrady commented on BMS_Software.ino
> +  const int NUM_CELLS = 8; // this should be in header?
Defined in header as CELL_COUNT

2022-04-24 22:24 UTC, ThisIsBrady commented on BMS_Software.ino
> +  else if ((cell_voltage[0] > PACK_UNDERVOLTAGE) && (cell_voltage[0] <= PACK_LOWVOLTAGE) && (low_voltage_state = true)) // following instances of low voltage
third condition needs == not =

2022-04-24 22:25 UTC, ThisIsBrady commented on BMS_Software.ino
> +  if ((cell_voltage[0] > PACK_UNDERVOLTAGE) && (cell_voltage[0] <= PACK_LOWVOLTAGE) && (low_voltage_state = false)) // first instance of low voltage
third condition needs == not =

2022-04-24 22:32 UTC, antrob25 requested changes
Nice job ;smirk;

2022-04-24 22:32 UTC, antrob25 commented on BMS_Software.h
> +// Created for 2019 Valkyrie by: Jacob Lipina, jrlwd5
Change year and Author

2022-04-24 22:32 UTC, antrob25 commented on BMS_Software.h
> +#define BUZZER_CTR_PIN			37
Have even spacing for pin names

2022-04-24 22:32 UTC, antrob25 commented on BMS_Software.h
> +#define OVERCURRENT           100000 //mA
Change to 120

2022-04-24 22:32 UTC, antrob25 commented on BMS_Software.h
> +#define CURRENT_ADC_MAX     	4096 //bits
Comment should be 4096 values not bits as it is 12 bit ADC resolution

2022-04-24 22:32 UTC, antrob25 commented on BMS_Software.h
> +#define PACK_SAFETY_LOW     	PACK_UNDERVOLTAGE - 4000 //mV	//Even though I shouldn't be need to measure a voltage lower than undervoltage
Remove as it is unused

2022-04-24 22:32 UTC, antrob25 commented on BMS_Software.ino
> +// Main cpp file (Needed to clarify that this is in c++)
Remove Uneeded comments like c++ files and asking Anthony about Github

2022-04-24 22:32 UTC, antrob25 commented on BMS_Software.ino
> +//Setup and Main Loop
Move global variables to the header file

2022-04-24 22:32 UTC, antrob25 commented on BMS_Software.ino
> +uint32_t batt_temp;   //TEMP_degC
Change to float

2022-04-24 22:32 UTC, antrob25 commented on BMS_Software.ino
> +int num_loop = 0; // battery temperature sensor state defualt to false in case of an error report
Specify int type for num_loop

2022-04-24 22:32 UTC, antrob25 commented on BMS_Software.ino
> +  if ((millis() - time_since_Rovecomm_update) >= ROVECOMM_UPDATE_DELAY)
Change telemetry to interrupt based not polling

2022-04-24 22:32 UTC, antrob25 commented on BMS_Software.ino
> +    time_since_Rovecomm_update = millis();
Use this last_update_time variable instead

2022-04-24 22:32 UTC, antrob25 commented on BMS_Software.ino
> +// Battery Managment System (BMS) Software System
Change spacing to 4 spaces

2022-04-24 22:32 UTC, antrob25 commented on BMS_Software.ino
> +    delay(DEBOUNCE_DELAY); // debounce delay is to check twice in a short period of time
There might be a Teensy Library for debouncing to correctly debounce the reading

2022-04-24 22:32 UTC, antrob25 commented on BMS_Software.ino
> +        if ((map(adc_reading, CELL_V_ADC_MIN, CELL_V_ADC_MAX, CELL_VOLTS_MIN, CELL_VOLTS_MAX) <= CELL_UNDERVOLTAGE)
Map function should be replaced to cell_voltages[i].

2022-04-24 22:32 UTC, antrob25 commented on BMS_Software.ino
> +void getOutVoltage(float &pack_out_voltage)
Change to getPackVoltage

2022-04-24 22:32 UTC, antrob25 commented on BMS_Software.ino
> +  pack_out_voltage = ((1269 * map(adc_reading, PACK_V_ADC_MIN, PACK_V_ADC_MAX, VOLTS_MIN, PACK_VOLTS_MAX)) / 1000); // 1269 is the voltage to analog signal ratio
Make 1269 into a constant called VoltageToSignalRatio

2022-04-24 22:32 UTC, antrob25 commented on BMS_Software.ino
> +      pack_undervoltage_state = true;
reset bool

2022-04-24 22:32 UTC, antrob25 commented on BMS_Software.ino
> +  meas_batt_temp[num_meas_batt_temp] = (1060 * (map(adc_reading, TEMP_ADC_MIN, TEMP_ADC_MAX, TEMP_MIN, TEMP_MAX)) / 1000); // function of measuring battery temp with
Make random numbers to into constants

2022-04-24 22:32 UTC, antrob25 commented on BMS_Software.ino
> +    digitalWrite(PACK_GATE_CTR_PIN, HIGH); // BMS Suicide
Remove the reenable

2022-04-25 08:52 UTC, antrob25 requested changes

2022-04-25 08:52 UTC, antrob25 commented on BMS_Software.ino
> +void asterisks()
Change Valkyrie to Prometheus

2022-05-21 18:47 UTC, merged